research_task:
  description: >
    Проведіть ретельний пошук новин за темою {topic} для поточного року 2025.
    Зберіть 10 найбільш релевантних новин із заголовками, зображеннями, описом та вмістом.
  expected_output: >
    Список новин у форматі JSON. Кожна новина має містити поля: title, image_url, excerpt, content.
  agent: "researcher"

reporting_task:
  description: >
    Проаналізуйте отримані дані та створіть унікальну новину із 100% унікальним копірайтом, написаним українською мовою.
    У вихідному JSON‑об'єкті повинні бути присутні такі поля:
      - title: Заголовок новини.
      - slug: URL-friendly версія заголовку, сформована з title (усі символи в нижньому регістрі, пробіли замінені на тире).
      - excerpt: Короткий опис новини.
      - content: Повний текст новини.
  expected_output: >
    JSON об'єкт з полями: title, slug, excerpt, content.
  agent: "reporting_analyst"
  output_file: "report.json"

publishing_task:
  description: >
    На основі даних з report.json сформуйте JSON-масив, де кожна новина має наступні поля:
      - title: Заголовок новини.
      - slug: URL-friendly версія заголовку (формується з title).
      - excerpt: Короткий опис новини.
      - content: Повний текст новини.
      - new_categori_id: Ідентифікатор категорії (1 – Будівництво/Ремонт, 2 – Краса).
      - image_url: URL зображення.
      - created_at: Дата створення (формат YYYY-MM-DD).
      - updated_at: Дата оновлення (формат YYYY-MM-DD).
  expected_output: "Новини успішно збережені у базі даних."
  agent: "db_publisher"
