research_task:
  description: >
    Проведіть ретельний пошук новин за темою {topic} для поточного року 2025.
    Зберіть достатню кількість релевантних новин із заголовками, зображеннями, описом та вмістом,
    щоб було з чого обрати найкращу новину для кожної категорії:
      - 1 – Будівництво/Ремонт
      - 2 – Краса.
  expected_output: >
    Список новин у форматі JSON. Кожна новина має містити поля: title, image_url, excerpt, content.
  agent: "researcher"

reporting_task:
  description: >
    Проаналізуйте отримані дані та створіть 2 унікальні новини із 100% унікальним копірайтом, написаним українською мовою.
    Для кожної категорії (1 – Будівництво/Ремонт та 2 – Краса) виберіть по одну найкращу новину.
    Переконайтеся, що у кожній новині:
      - вміст (content) не менше 1000 символів,
      - рівень унікальності не менше 70%.
    У вихідному JSON‑об'єкті повинні бути присутні наступні поля:
      - title: Заголовок новини.
      - slug: URL-friendly версія заголовку (формується з title: всі символи в нижньому регістрі, пробіли замінені на тире).
      - excerpt: Короткий опис новини.
      - content: Повний текст новини.
  expected_output: >
    JSON об'єкт, який містить масив із 2 об'єктів, де кожен має поля: title, slug, excerpt, content.
  agent: "reporting_analyst"
  output_file: "report.json"

publishing_task:
  description: >
    На основі даних з report.json сформуйте JSON-масив, де кожна новина має наступні поля:
      - title: Заголовок новини.
      - slug: URL-friendly версія заголовку (формується з title).
      - excerpt: Короткий опис новини.
      - content: Повний текст новини.
      - new_categori_id: Ідентифікатор категорії (1 – Будівництво/Ремонт, 2 – Краса).
      - image_url: URL зображення.
      - created_at: Дата створення (формат YYYY-MM-DD).
      - updated_at: Дата оновлення (формат YYYY-MM-DD).
  expected_output: "Новини успішно збережені у базі даних."
  agent: "db_publisher"
