research_task:
  description: "Проведіть ретельний пошук новин за темою {topic} для поточного року 2025. Зберіть 10 найбільш релевантних новин з заголовками, зображеннями, описом та вмістом."
  expected_output: "Список за темою {topic} 1 тема одна новина."
  agent: "researcher"

reporting_task:
  description: "Проаналізуйте отримані дані та створіть повноцінну новину із унікальним копірайтом, написаним українською мовою, який буде легким для читання."
  expected_output: "Детальний звіт з основними темами, відформатований як розмітка (без ```)."
  agent: "reporting_analyst"
  output_file: "report.json"

publishing_task:
  description: "На основі унікальних новин створеного копірайту, додайте новини до бази даних. Для кожної новини підберіть зображення, схоже на новинний матеріал.
                Інформацію адаптуй під данні у бд з такими атрибутами як: заголовок, опис, вміст, зображення. id, title, slug, excerpt, content,new_categori_id (1-Будівництво/Ремонт , 2 Краса) image_url, created_at, updated_at."
  expected_output: "Новини успішно збережені у базі даних."
  agent: "db_publisher"
